# Generated by Django 5.1.7 on 2025-05-16 07:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_expopushtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='createAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='second_review',
            name='createAt',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
