# Generated by Django 5.1.7 on 2025-05-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_alter_review_createat_alter_second_review_createat'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='ead_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='السعر بالعيد'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='holiday_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='السعر بالعطلة'),
        ),
    ]
