# Generated by Django 5.1.7 on 2025-05-26 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0014_pushtoken_delete_expopushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='name_of_realestate',
            field=models.CharField(max_length=50, null=True, verbose_name='اسم المزرعة'),
        ),
    ]
