# Generated by Django 5.1.7 on 2025-05-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0016_alter_realestate_name_of_realestate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='name_of_realestate',
            field=models.CharField(default=' ', max_length=50, null=True, verbose_name='اسم المزرعة'),
        ),
    ]
