# Generated by Django 5.1.7 on 2025-05-27 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0017_alter_realestate_name_of_realestate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='cars',
            field=models.IntegerField(default=0, verbose_name='عدد السيارات المتاحة في الكراج'),
        ),
        migrations.CreateModel(
            name='Custom_Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('write_message', 'write_message')], default='write_message', max_length=50)),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('createAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('seen', models.BooleanField(default=False)),
                ('user_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Custom_Notification', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
