# Generated by Django 5.1.7 on 2025-05-27 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0018_realestate_cars_custom_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='checkin',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='بداية الحجز'),
        ),
        migrations.AddField(
            model_name='realestate',
            name='checkout',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='انتهاء الحجز'),
        ),
    ]
