# Generated by Django 5.1.7 on 2025-05-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0019_realestate_checkin_realestate_checkout'),
    ]

    operations = [
        migrations.CreateModel(
            name='phones_admins',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.IntegerField(default=0, null=True, verbose_name='رقم الادمن')),
                ('name', models.CharField(max_length=30, null=True, verbose_name='اسم الادمن')),
            ],
        ),
    ]
