# Generated by Django 5.1.7 on 2025-05-29 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0020_phones_admins'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='phones_admins',
            new_name='Phones_Help',
        ),
    ]
