# Generated by Django 5.1.7 on 2025-05-30 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0021_rename_phones_admins_phones_help'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='period',
            field=models.CharField(choices=[('بالليلة', 'باليوم'), ('بالشهر', 'بالشهر')], max_length=30, null=True, verbose_name='باليوم او بالشهر؟'),
        ),
    ]
