# Generated by Django 5.1.7 on 2025-05-30 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0022_alter_realestate_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='period',
            field=models.CharField(choices=[('باليوم', 'باليوم'), ('بالشهر', 'بالشهر')], default='باليوم', max_length=30, null=True, verbose_name='باليوم او بالشهر؟'),
        ),
    ]
