# Generated by Django 5.1.7 on 2025-08-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0023_alter_realestate_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phones_help',
            name='phone',
            field=models.CharField(max_length=30, null=True, verbose_name='رقم الادمن'),
        ),
        migrations.AlterField(
            model_name='realestate',
            name='period',
            field=models.CharField(choices=[('باليوم', 'باليوم'), ('بالشهر', 'بالشهر')], max_length=30, null=True, verbose_name='باليوم او بالشهر؟'),
        ),
    ]
